default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: KinAraiDeeAPI_development
  host: <%= ENV.fetch('DB_HOST') %>
  port: <%= ENV.fetch('DB_PORT') %>
  username: postgres

test:
  <<: *default
  database: KinAraiDeeAPI_test
  host: <%= ENV.fetch('DB_HOST') %>
  port: <%= ENV.fetch('DB_PORT') %>
  username: postgres

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
